services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Wamb\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Resources/'
      - '../../TaggingBundle.php'
      - '../../Tests/'
      -
  #Wamb\TaggingBundle\Application\Command\CreateTag\CreateTagHandler: ~
  #Wamb\TaggingBundle\Infrastructure\Symfony\Validators\TagCommandValidator: ~
